version: '3.9'
services:
  postgres:
    image: postgis/postgis:9.6-2.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      # - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  webserver:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
    environment:
      - DB_URI=postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command:
      # run migration first
      bash -c "$$(cd routes && PYTHONPATH=.. alembic upgrade head)
      && uvicorn --host 0.0.0.0 --port 8000 routes.api:app --reload"
    stdin_open: true
    tty: true
