"""Rename model

Revision ID: e3445f85dec6
Revises: f8d3426212fd
Create Date: 2021-07-16 22:55:46.318983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3445f85dec6'
down_revision = 'f8d3426212fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
